// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasiQa94EXLns9Zjhj_ep_5W_BgIEmxqY',
    appId: '1:781922287934:web:9fbf3f9b33bc1742e2ac6f',
    messagingSenderId: '781922287934',
    projectId: 'pclink-34bfa',
    authDomain: 'pclink-34bfa.firebaseapp.com',
    databaseURL: 'https://pclink-34bfa-default-rtdb.firebaseio.com',
    storageBucket: 'pclink-34bfa.firebasestorage.app',
    measurementId: 'G-522D04T73K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnLPcUtCWZK41nC-PqaOx9briB-Bgt8s',
    appId: '1:781922287934:android:8f85f6ccf6b1a0f9e2ac6f',
    messagingSenderId: '781922287934',
    projectId: 'pclink-34bfa',
    databaseURL: 'https://pclink-34bfa-default-rtdb.firebaseio.com',
    storageBucket: 'pclink-34bfa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasiQa94EXLns9Zjhj_ep_5W_BgIEmxqY',
    appId: '1:781922287934:web:a8ffa521b3f69897e2ac6f',
    messagingSenderId: '781922287934',
    projectId: 'pclink-34bfa',
    authDomain: 'pclink-34bfa.firebaseapp.com',
    databaseURL: 'https://pclink-34bfa-default-rtdb.firebaseio.com',
    storageBucket: 'pclink-34bfa.firebasestorage.app',
    measurementId: 'G-4DWKJ1XW4H',
  );
}
